
[functions.invite-militante]
enabled = true
verify_jwt = true
import_map = "./functions/invite-militante/deno.json"
entrypoint = "./functions/invite-militante/index.ts"

[functions.send-mass-email]
enabled = true
verify_jwt = true
entrypoint = "./functions/send-mass-email/index.ts"
